[package]
name = "s3-scrubber"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "0.55", default-features = false, features = [
    "rustls",
] }
aws-sdk-s3 = "0.26"
aws-smithy-http = "0.55"
aws-types = "0.55"

reqwest = { version = "0.11", features = ["json"] }
chrono = { version = "0.4", features = ["serde"] }
either = "1.8"

tokio = { version = "1.17", features = [
    "macros",
    "sync",
    "fs",
    "io-util",
    "rt-multi-thread",
] }
tokio-rustls = "0.24"
async-stream = "0.3.5"
tokio-stream = "0.1.14"
futures-util = "0.3.28"
itertools = "0.11"
histogram = "0.7.4"

anyhow = { version = "1.0", features = ["backtrace"] }

hex = "0.4"
thiserror = "1.0"
rand = "0.8"
bytes = "1.4"
bincode = "1.3"
crc32c = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "2.2"

atty = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
clap = { version = "4.3.22", features = ["derive"] }
